# Generated by Django 4.1.1 on 2022-09-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='articulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
